[project]
name = "openff-utilities"
dependencies = [ "mypy==1.6", "pytest-cov>=5.0.0,<6", "types-setuptools>=75.2.0.20241019,<76", "types-toml>=0.10.8.20240310,<0.11", "pytest", "importlib-resources"]

[tool.pixi.project]
channels = ["conda-forge", "openeye"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.dependencies]
pip = ">=24.2,<25"
python = ">=3.10,<4"
